# Generated by Django 4.1.7 on 2023-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='signature',
            field=models.CharField(default='Firmas', max_length=100),
        ),
    ]
