# Generated by Django 4.1.7 on 2023-04-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comments_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=3)),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('date', models.DateField(null=True)),
                ('signature', models.CharField(default='Firmas ', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
